(()=>{
const css=`
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#0b0f15;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans JP",sans-serif}button{font:inherit;color:inherit;cursor:pointer}.app{height:100%;display:grid;grid-template-rows:58px 48px 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 14px;background:#131923;border-bottom:1px solid #313a47}.brand{font-weight:800}.brand b{color:#45d5ef}.btn{border:1px solid #3b4654;background:#202833;border-radius:9px;padding:8px 10px}#tabs{display:flex;gap:5px;overflow:auto;padding:5px 9px;background:#171d26;border-bottom:1px solid #303946}.tab{border:0;background:transparent;color:#adb7c4;padding:8px 11px;white-space:nowrap;border-bottom:3px solid transparent}.tab.on{color:#64e0f5;border-color:#37cde9}main{min-height:0;display:grid;grid-template-columns:200px 1fr 285px}aside{padding:12px;background:#161c24;overflow:auto}.left{border-right:1px solid #303946}.right{border-left:1px solid #303946}#view{position:relative;overflow:hidden;background:radial-gradient(circle at 50% 40%,#303a48,#171d26 52%,#090c11)}canvas{display:block;width:100%;height:100%;touch-action:none}#list{display:grid;gap:6px}.item{border:1px solid #394451;background:#202832;border-radius:9px;padding:8px;text-align:left}.item.on{border-color:#42d1eb;background:#15343e}.badge{display:inline-block;background:#153b46;color:#71e0f4;border-radius:999px;padding:5px 8px;font-size:12px}h2{margin:8px 0}p{color:#c5cdd7;line-height:1.65}.info{margin-top:12px;padding:11px;border:1px solid #37424f;background:#202731;border-radius:11px;line-height:1.55}.controls{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px}.hint{position:absolute;left:10px;top:10px;background:#0009;padding:7px 9px;border-radius:8px;font-size:12px;color:#c1cad4}.menu{position:absolute;inset:0;z-index:20;background:#0d1118f7;padding:24px;overflow:auto}.menu.hide{display:none}.menuBox{max-width:900px;margin:auto}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{min-height:120px;border:1px solid #3a4552;background:#1b222c;border-radius:15px;padding:14px;text-align:left}.card b{display:block;font-size:19px;margin-bottom:7px}.card span{color:#aeb9c6}@media(max-width:760px){main{grid-template-columns:1fr}.left{display:none}.right{position:absolute;right:7px;top:112px;width:245px;max-height:47%;z-index:6;border:1px solid #394451;border-radius:12px;background:#161c24ef}.cards{grid-template-columns:1fr 1fr}}`;
document.head.insertAdjacentHTML("beforeend","<style>"+css+"</style>");
document.getElementById("app").outerHTML=`<div class="app"><header><div class="brand"><b>⬢</b> 中学校理科 人体3Dアトラス <small style="color:#77828f">web</small></div><div><button class="btn" id="menuBtn">目次</button> <button class="btn" id="resetBtn">全体表示</button></div></header><div id="tabs"></div><main><aside class="left"><h3>器官・臓器</h3><div id="list"></div></aside><section id="view"><canvas id="cv"></canvas><div class="hint">ドラッグ：360°回転　クリック：臓器選択</div><div class="menu" id="menu"><div class="menuBox"><button class="btn" id="closeBtn" style="float:right">閉じる</button><h1>人体アトラス 目次</h1><p>学習したい内容を選んでください。</p><div class="cards" id="cards"></div></div></div></section><aside class="right"><span class="badge" id="badge">全身</span><h2 id="name">人体</h2><p id="desc">人体を回転して器官の位置関係を観察します。</p><div class="info"><b>中学校理科ポイント</b><div id="point">器官どうしの位置と働きを確認しましょう。</div></div><div class="controls"><button class="btn" id="bodyBtn">人体 ON</button><button class="btn" id="boneBtn">骨格 ON</button><button class="btn" id="labelBtn">名称 ON</button><button class="btn" id="isoBtn">単独表示</button></div></aside></main></div>`;
const systems=[["全身","人体・骨格・内臓"],["骨格","頭蓋骨・脊柱・肋骨・骨盤・手足"],["循環器系","心臓と血液循環"],["呼吸器系","気管・肺と呼吸"],["消化器系","胃・肝臓・腸"],["泌尿器系","腎臓・ぼうこう"],["神経系","脳・せきずい"]];
const O=[["brain","脳","神経系",0,-140,2,27,23,"#d9b39f","情報を処理し、からだへ命令を出します。","脳とせきずいは中枢神経です。"],["spine","せきずい","神経系",0,-35,-12,5,90,"#e2d4a7","脳とからだをつなぎます。","反射ではせきずいが中枢になる場合があります。"],["trachea","気管","呼吸器系",0,-86,9,7,29,"#c5b092","空気を肺へ運びます。","気管は左右の気管支に分かれます。"],["lungL","左肺","呼吸器系",-25,-48,5,21,37,"#d99898","肺胞で気体交換をします。","酸素と二酸化炭素を交換します。"],["lungR","右肺","呼吸器系",25,-48,5,22,39,"#d99898","肺胞で気体交換をします。","呼吸運動には横隔膜などが関係します。"],["heart","心臓","循環器系",5,-30,26,18,25,"#d6525a","血液を送り出すポンプです。","心臓には4つの部屋があります。"],["liver","肝臓","消化器系",16,18,14,35,18,"#774136","養分の貯蔵などを行います。","小腸で吸収された養分の一部が運ばれます。"],["stomach","胃","消化器系",-18,39,19,17,25,"#c77a6b","食物を胃液と混ぜます。","胃液には塩酸と消化酵素が含まれます。"],["kidL","左腎臓","泌尿器系",-25,49,-3,11,19,"#8b5044","血液から不要物を取り除きます。","尿をつくり尿管へ送ります。"],["kidR","右腎臓","泌尿器系",25,49,-3,11,19,"#8b5044","血液から不要物を取り除きます。","排出に関係する器官です。"],["small","小腸","消化器系",0,91,13,30,31,"#d6a77f","養分の多くを吸収します。","柔毛で表面積を大きくしています。"],["large","大腸","消化器系",0,95,3,38,40,"#ad8468","主に水分を吸収します。","小腸の外側を囲むようにあります。"],["bladder","ぼうこう","泌尿器系",0,147,13,15,18,"#d5bd90","尿を一時的にためます。","尿は腎臓→尿管→ぼうこう→尿道と移動します。"]];
let g="全身",sel=null,ay=0,ax=0,z=1.25,drag=false,lx=0,ly=0,moved=false,bodyOn=true,boneOn=true,labelOn=true,iso=false;
const $=id=>document.getElementById(id),cv=$("cv"),ctx=cv.getContext("2d"),view=$("view");
function rot(x,y,d){const c=Math.cos(ay),s=Math.sin(ay),xx=x*c-d*s,dd=x*s+d*c,C=Math.cos(ax),S=Math.sin(ax);return[xx,y*C-dd*S,y*S+dd*C]}
function pr(x,y,d){const r=rot(x,y,d),k=560/(560+r[2]);return[cv.clientWidth/2+r[0]*z*k,cv.clientHeight/2+r[1]*z*k,r[2],k]}
function ln(a,b,w,c){const p=pr(...a),q=pr(...b);ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.strokeStyle=c;ctx.lineWidth=w*z;ctx.lineCap="round";ctx.stroke()}
function body(){if(!bodyOn||g==="骨格")return;ctx.save();ctx.fillStyle="rgba(213,171,148,.22)";ctx.strokeStyle="rgba(245,205,183,.7)";ctx.lineWidth=2;let h=pr(0,-142,-12);ctx.beginPath();ctx.ellipse(h[0],h[1],34*z,42*z,0,0,6.29);ctx.fill();ctx.stroke();let a=[[-18,-104,-8],[-43,-91,-5],[-49,-35,-2],[-38,60,0],[-27,83,0],[27,83,0],[38,60,0],[49,-35,-2],[43,-91,-5],[18,-104,-8]].map(p=>pr(...p));ctx.beginPath();ctx.moveTo(a[0][0],a[0][1]);a.slice(1).forEach(p=>ctx.lineTo(p[0],p[1]));ctx.closePath();ctx.fill();ctx.stroke();ln([-42,-80,-4],[-65,78,0],21,"rgba(213,171,148,.25)");ln([42,-80,-4],[65,78,0],21,"rgba(213,171,148,.25)");ln([-22,78,0],[-32,255,5],29,"rgba(213,171,148,.25)");ln([22,78,0],[32,255,5],29,"rgba(213,171,148,.25)");ctx.restore()}
function bones(){if(!(g==="骨格"||(g==="全身"&&boneOn)))return;const c="#eee6d6";ln([0,-112,0],[0,72,0],5,c);ln([-37,-76,0],[37,-76,0],5,c);ln([-37,-76,0],[-58,-5,0],6,c);ln([-58,-5,0],[-67,76,0],5,c);ln([37,-76,0],[58,-5,0],6,c);ln([58,-5,0],[67,76,0],5,c);ln([-25,80,0],[-30,174,0],8,c);ln([-30,174,0],[-33,252,0],6,c);ln([25,80,0],[30,174,0],8,c);ln([30,174,0],[33,252,0],6,c);let s=pr(0,-142,0);ctx.strokeStyle=c;ctx.lineWidth=4*z;ctx.beginPath();ctx.ellipse(s[0],s[1],25*z,31*z,0,0,6.29);ctx.stroke();for(let i=0;i<8;i++){let p=pr(0,-67+i*11,0);ctx.beginPath();ctx.ellipse(p[0],p[1],(38-i*.8)*z,13*z,0,0,6.29);ctx.stroke()}let q=pr(0,82,0);ctx.lineWidth=6*z;ctx.beginPath();ctx.ellipse(q[0],q[1],34*z,22*z,0,0,6.29);ctx.stroke()}
function show(o){if(g==="骨格")return false;if(iso)return sel&&o[0]===sel[0];return g==="全身"||o[2]===g}
function organ(o){const p=pr(o[3],o[4],o[5]),rx=o[6]*z*p[3],ry=o[7]*z*p[3];ctx.beginPath();ctx.ellipse(p[0],p[1],rx,ry,0,0,6.29);ctx.fillStyle=o[8];ctx.fill();ctx.strokeStyle=sel&&sel[0]===o[0]?"#6cecff":"#ffffff55";ctx.lineWidth=sel&&sel[0]===o[0]?3:1;ctx.stroke();if(labelOn){ctx.font="12px sans-serif";ctx.textAlign="center";ctx.lineWidth=4;ctx.strokeStyle="#000";ctx.fillStyle="#fff";ctx.strokeText(o[1],p[0],p[1]-ry-6);ctx.fillText(o[1],p[0],p[1]-ry-6)}}
function draw(){ctx.clearRect(0,0,cv.clientWidth,cv.clientHeight);body();bones();O.filter(show).map(o=>[o,rot(o[3],o[4],o[5])[2]]).sort((a,b)=>a[1]-b[1]).forEach(v=>organ(v[0]))}
function resize(){const r=view.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);cv.width=Math.max(1,r.width*d);cv.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function tabs(){$("tabs").innerHTML=systems.map(s=>'<button class="tab '+(s[0]===g?'on':'')+'" data-g="'+s[0]+'">'+s[0]+'</button>').join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setG(b.dataset.g))}
function list(){const a=O.filter(o=>g==="全身"||o[2]===g);$("list").innerHTML=a.length?a.map(o=>'<button class="item '+(sel&&sel[0]===o[0]?'on':'')+'" data-i="'+o[0]+'">'+o[1]+'</button>').join(""):'<span style="color:#8994a2">骨格を表示中</span>';document.querySelectorAll(".item").forEach(b=>b.onclick=()=>select(b.dataset.i))}
function select(id){sel=O.find(o=>o[0]===id)||null;if(sel){$("badge").textContent=sel[2];$("name").textContent=sel[1];$("desc").textContent=sel[9];$("point").textContent=sel[10]}list();draw()}
function setG(x){g=x;sel=null;iso=false;tabs();list();$("badge").textContent=x;$("name").textContent=x==="骨格"?"骨格":"人体";$("desc").textContent=x==="骨格"?"全身の骨格を観察できます。":"器官の位置関係を観察できます。";$("point").textContent=x==="骨格"?"骨はからだを支え、筋肉と協力して運動します。":"器官の位置と働きを確認しましょう。";$("menu").classList.add("hide");draw()}
$("menuBtn").onclick=()=>$("menu").classList.remove("hide");$("closeBtn").onclick=()=>$("menu").classList.add("hide");$("resetBtn").onclick=()=>{ay=0;ax=0;z=1.25;iso=false;draw()};$("bodyBtn").onclick=function(){bodyOn=!bodyOn;this.textContent="人体 "+(bodyOn?"ON":"OFF");draw()};$("boneBtn").onclick=function(){boneOn=!boneOn;this.textContent="骨格 "+(boneOn?"ON":"OFF");draw()};$("labelBtn").onclick=function(){labelOn=!labelOn;this.textContent="名称 "+(labelOn?"ON":"OFF");draw()};$("isoBtn").onclick=()=>{if(sel){iso=!iso;draw()}};
cv.onpointerdown=e=>{drag=true;moved=false;lx=e.clientX;ly=e.clientY;cv.setPointerCapture(e.pointerId)};cv.onpointermove=e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;ay+=dx*.009;ax=Math.max(-.6,Math.min(.6,ax+dy*.006));lx=e.clientX;ly=e.clientY;draw()};cv.onpointerup=e=>{drag=false;if(!moved){const r=cv.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let best=null,bestD=1e9;O.filter(show).forEach(o=>{const p=pr(o[3],o[4],o[5]),rx=o[6]*z*p[3],ry=o[7]*z*p[3],d=((mx-p[0])/rx)**2+((my-p[1])/ry)**2;if(d<=1&&d<bestD){best=o;bestD=d}});if(best)select(best[0])}};cv.addEventListener("wheel",e=>{e.preventDefault();z=Math.max(.7,Math.min(2.4,z*(e.deltaY<0?1.08:.92)));draw()},{passive:false});
$("cards").innerHTML=systems.map(s=>'<button class="card" data-g="'+s[0]+'"><b>'+s[0]+'</b><span>'+s[1]+'</span></button>').join("");document.querySelectorAll(".card").forEach(b=>b.onclick=()=>setG(b.dataset.g));tabs();list();setTimeout(resize,30);addEventListener("resize",resize);
})();