import {useState} from 'react';
export default function EarHighSchool(){
 const [tab,setTab]=useState('signal'),[step,setStep]=useState(0),[pitch,setPitch]=useState(1),[loud,setLoud]=useState(false),[balance,setBalance]=useState(false);
 const positions=[.78,.46,.2],peak=positions[pitch],names=['低い音','中くらいの音','高い音'];
 const wave=Array.from({length:101},(_,i)=>{const x=i/100,amp=(loud?42:24)*Math.exp(-(((x-peak)/.16)**2));return `${i?'L':'M'}${35+x*340} ${128-amp}`;}).join(' ');
 const messages=['基底膜の振動で、有毛細胞の毛束が曲がります。','毛束の曲がりに応じ、有毛細胞の膜電位が変わります（受容器電位）。','神経伝達物質の放出が変化し、聴神経に活動電位として情報が伝わります。'];
 return <section className="organ-lab ear-high-school" aria-label="高校生物の耳の探究"><h4>高校生物：刺激の受容と情報伝達</h4><p>耳を受容器の例として、物理的な刺激から神経の情報への変化を考えます。</p><div className="lab-controls" aria-label="高校の耳の観察テーマ">{[['signal','有毛細胞と神経'],['pitch','音の高さと大きさ'],['balance','聴覚と平衡感覚']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div>
 {tab==='signal'&&<><svg viewBox="0 0 420 230" role="img" className="organ-diagram" aria-label={`有毛細胞と聴神経の拡大模式図。${messages[step]}`}><path d="M45 87L260 87" stroke="#93aab9" strokeWidth="9"/><path d="M128 90C83 106 93 187 145 187C195 187 205 109 165 90Z" fill="#c3dfdf" stroke="#5f959c" strokeWidth="3"/><g transform={`rotate(${step>0?-18:0} 145 89)`} stroke="#557f8d" strokeWidth="5">{[0,1,2,3].map(i=><path key={i} d={`M${128+i*10} 88V${58-i*5}`}/>)}</g><path d="M42 199L250 199" stroke="#aa8680" strokeWidth="6"/>{step===2&&[0,1,2].map(i=><circle key={i} cx={136+i*9} cy="193" r="3" fill="#c38b20"/>)}<path d="M155 210L360 210" stroke={step===2?'#c38b20':'#b2bec5'} strokeWidth="7"/><g fill="#405e6b" fontSize="13"><text x="58" y="35">毛束（感覚毛）</text><text x="218" y="120">有毛細胞</text><text x="272" y="190">聴神経 → 脳</text><text x="16" y="220">基底膜</text></g></svg><div className="lab-controls" aria-label="振動から神経への段階">{['1. 振動を受ける','2. 細胞の膜電位が変わる','3. 神経へ伝える'].map((s,i)=><button key={s} aria-pressed={step===i} onClick={()=>setStep(i)}>{s}</button>)}</div><p className="lab-explanation" aria-live="polite">{messages[step]}</p><p>有毛細胞で生じる受容器電位と、聴神経を伝わる活動電位を区別します。神経伝達物質は細胞どうしの情報伝達に関わります。</p><details><summary>発展：毛束が曲がると何が起こる？</summary><p>機械的な変形によってイオンチャネルの開閉が変わり、イオンの流れが膜電位を変化させます。変化の向きに応じて神経伝達物質の放出も変わります。これは、刺激の受容と神経の興奮をつなぐ例です。</p></details></>}
 {tab==='pitch'&&<><h4>蝸牛をほどいて、場所の違いを見る</h4><div className="lab-controls" aria-label="音の高さ">{names.map((n,i)=><button key={n} aria-pressed={pitch===i} onClick={()=>setPitch(i)}>{n}</button>)}<button aria-pressed={loud} onClick={()=>setLoud(!loud)}>{loud?'音を小さくする':'同じ高さで音を大きくする'}</button></div><svg viewBox="0 0 420 210" role="img" className="organ-diagram" aria-label={`${names[pitch]}：${pitch===2?'入り口側':pitch===0?'奥側':'中間'}の基底膜の振動が大きい模式図`}><path d="M35 125L375 92V164L35 135Z" fill="#d5e5e7" stroke="#8dafb7" strokeWidth="2"/><path d={wave} fill="none" stroke="#c38b20" strokeWidth="4"/><circle cx={35+peak*340} cy={128-(loud?42:24)} r="5" fill="#c38b20"/><g fill="#476372" fontSize="13"><text x="24" y="35">入り口（基部）</text><text x="290" y="35">奥（頂部）</text><text x="25" y="59">狭く硬い</text><text x="292" y="59">広く柔らかい</text><text x="135" y="193">基底膜：振動の大きい場所</text></g></svg><p className="lab-explanation" aria-live="polite">{names[pitch]}は{pitch===2?'蝸牛の入り口に近い基部':pitch===0?'奥にある頂部':'基部と頂部の間'}で強く受容されます。{loud?'音を大きくしても、同じ高さなら受容される主な場所は変わりません。':'高さを変えて、振動が大きい場所を比べましょう。'}</p><p>音の高さは振動数に関係し、蝸牛では主に受容する場所が変わります。音の大きさは振動の強さに関係します。この図では高さと大きさを別々に変えられます。</p></>}
 {tab==='balance'&&<><div className="lab-controls"><button aria-pressed={!balance} onClick={()=>setBalance(false)}>頭を回す</button><button aria-pressed={balance} onClick={()=>setBalance(true)}>頭を傾ける・直線的に動く</button></div><svg viewBox="0 0 420 220" role="img" className="organ-diagram" aria-label={balance?'前庭の耳石器が、頭の傾きや直線加速度を受容する模式図':'三半規管が頭の回転の変化を受容する模式図'}><g fill="none" stroke={balance?'#b6bcc8':'#a47b31'} strokeWidth="9"><ellipse cx="183" cy="83" rx="60" ry="48"/><ellipse cx="238" cy="95" rx="37" ry="56" transform="rotate(40 238 95)"/><ellipse cx="187" cy="117" rx="68" ry="22"/></g><ellipse cx="232" cy="152" rx="29" ry="23" fill={balance?'#ebce8a':'#d9dce4'} stroke="#978baa" strokeWidth="3"/><path d="M260 151C327 117 333 199 277 181C250 170 291 150 299 174" stroke="#70929f" strokeWidth="8" fill="none"/><g fontSize="13" fill="#485f6c"><text x="76" y="25">三半規管</text><text x="47" y="184">前庭（耳石器）</text><text x="293" y="213">蝸牛：聴覚</text></g></svg><p className="lab-explanation" aria-live="polite">{balance?'前庭の耳石器は、重力に対する頭の傾きや直線加速度を受け取ります。':'三半規管は、頭の回転の変化を受け取ります。3つの管は異なる向きに配置されています。'}</p><table className="school-enzyme-table"><thead><tr><th>感覚</th><th>主な受容部位</th><th>刺激</th></tr></thead><tbody><tr><td>聴覚</td><td>蝸牛</td><td>音の振動</td></tr><tr><td>平衡感覚</td><td>三半規管</td><td>回転の変化</td></tr><tr><td>平衡感覚</td><td>前庭の耳石器</td><td>傾き・直線加速度</td></tr></tbody></table></>}
 <details className="school-check"><summary>高校の観察：自分の言葉で説明しよう</summary><p>① 鼓膜の振動は、そのまま神経を伝わるのだろうか？<br/>② 音を高くする操作と、大きくする操作はどう違う？<br/>③ 三半規管は音を聞くための器官だろうか？</p><details><summary>説明の例</summary><p>① 蝸牛の有毛細胞で刺激が受容され、神経の情報へ変わります。② 高さを変えると主な受容場所が変わり、大きさを変えると振動の強さが変わります。③ 三半規管は平衡感覚に関わり、聴覚は蝸牛が担います。</p></details></details>
 <p className="lab-note">高校「生物」の刺激の受容と反応に関連する発展教材です。図の形・振動・曲がり方は模式表現で、実寸や実際の電位・振動数を再現しません。音声は再生しません。</p><a className="lab-source" href="https://www.nidcd.nih.gov/health/balance-disorders" target="_blank" rel="noreferrer">参考：NIH/NIDCD・平衡感覚</a>
 </section>;
}
