import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,BookOpen,ChevronRight,Focus,Info,Layers3,RotateCcw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,LEARNING_LAYERS,LEARNING_VISIBLE_SYSTEMS,ORGAN_VISIBLE_SYSTEMS,SYSTEMS,EXPLANATIONS,explanation,localizeAnatomyName,type Atlas,type Concept,type SceneState,type View} from './anatomy';
import LearningPanel,{type Lesson,type LessonId} from './learning';
import OrganModel from './organ-model';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const [organModel,setOrganModel]=useState<'heart'|'eye'|null>(null);
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[lessonOpen,setLessonOpen]=useState(false),[lessonId,setLessonId]=useState<LessonId>('heart'),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});const atlasUrl=new URL('models/atlas.json',document.baseURI);fetch(atlasUrl,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('人体データを読み込めませんでした。');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(LEARNING_LAYERS.map(layer=>[layer.id,atlas?.parts.filter(p=>layer.systems.includes(p.system)).length??0])),[atlas]);
 const activeLayers=LEARNING_LAYERS.filter(layer=>counts[layer.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||localizeAnatomyName(c.name).toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggleLayer=(layer:typeof LEARNING_LAYERS[number])=>{setDetails(false);setState(s=>{const enabled=layer.systems.every(id=>s.visible.includes(id));return {...s,selected:[],isolate:false,visible:enabled?s.visible.filter(id=>!layer.systems.includes(id)):[...new Set([...s.visible,...layer.systems])]};});};
 const focusLesson=(lesson:Lesson)=>{setLessonId(lesson.id);const selected=lesson.focusNames?.flatMap(name=>atlas?.concepts.filter(c=>c.name.toLowerCase()===name.toLowerCase()).flatMap(c=>c.elements)??[])??[];setDetails(false);setChosen(null);setState(s=>({...s,visible:lesson.systems,selected:[...new Set(selected)],isolate:false,rotate:false,reset:s.reset+1}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const viewNames:Record<View,string>={'three-quarter':'斜め前','front':'正面','side':'側面','back':'背面'};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> 3D人体アトラス</div><h1>人体アトラス<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'}個の3Dパーツ <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="アトラスの操作"><Button variant="ghost" className={lessonOpen?'active':''} onClick={()=>{setDetails(false);setPanel(null);setLessonOpen(true);}} aria-label="授業で学ぶ"><BookOpen size={18}/><span>授業で学ぶ</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="人体を検索"><Search size={18}/><span>構造を検索</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="このアトラスについて" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="人体の学習レイヤー">
   <div className="panel-heading"><span>学習する部位</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="学習レイヤーを閉じる"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeLayers.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={LEARNING_VISIBLE_SYSTEMS.every(id=>state.visible.includes(id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:LEARNING_VISIBLE_SYSTEMS}))}>学習用</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>骨格</Button><Button variant="ghost" aria-pressed={ORGAN_VISIBLE_SYSTEMS.every(id=>state.visible.includes(id))&&state.visible.length===ORGAN_VISIBLE_SYSTEMS.length} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:ORGAN_VISIBLE_SYSTEMS}))}>内臓</Button></div>
   <div className="system-list">{activeLayers.map(layer=>{const enabled=layer.systems.some(id=>state.visible.includes(id));const checked=layer.systems.every(id=>state.visible.includes(id));return <div className={`system-row ${enabled?'enabled':''}`} key={layer.id}><Button variant="ghost" className="system-name" title={`${layer.name}だけを表示`} onClick={()=>setState(v=>({...v,visible:layer.systems,isolate:false,selected:[]}))}><span className="system-dot" style={{background:layer.color}}/>{layer.name}<span className="system-count">{counts[layer.id]}</span></Button><Switch checked={checked} onCheckedChange={()=>toggleLayer(layer)} aria-label={`${layer.name}を表示`} /></div>})}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()}個のパーツを表示</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>すべて隠す</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="人体を検索"><div className="panel-heading"><span>構造を検索</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="検索を閉じる"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>localizeAnatomyName(c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="心臓、太ももの骨、視神経…" aria-label="名前から人体の構造を検索" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>一致する構造がありません。</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{localizeAnatomyName(c.name)}</span><span className="small-number">{c.elements.length}個</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'最大80件を表示しています。より細かい構造は検索語を追加してください。':'主な器官名や、体の構造名を入力してください。日本語・英語のどちらでも検索できます。'}</p></section>}
  <LearningPanel open={lessonOpen} lessonId={lessonId} onClose={()=>setLessonOpen(false)} onLessonChange={setLessonId} onFocus={focusLesson} onModel={kind=>{setLessonOpen(false);setOrganModel(kind);}}/>
  {organModel&&atlas&&<OrganModel key={organModel} atlas={atlas} kind={organModel} onClose={()=>{setOrganModel(null);setLessonOpen(true);}}/>}
  <nav className="view-controls glass" aria-label="視点コントロール">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1}))} title={`${viewNames[v]}から見る`} aria-label={`${viewNames[v]}から見る`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" aria-label="視点と表示をリセット" title="リセット" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?localizeAnatomyName(chosen.name):'選択中の構造'):'成人男性の人体モデル'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="学習レイヤーを開く"><Layers3 size={20}/><span>学習レイヤー</span></Button><div className="interaction-tip"><strong>3Dモデルを操作</strong><span>ドラッグで回転 · ピンチで拡大縮小 · タップで選択</span></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="視点と選択をリセット"><RotateCcw size={18}/><span>リセット</span></Button></div>
  <footer className="studio-footer"><span>ドラッグで回転 <b>·</b> ピンチで拡大縮小 <b>·</b> タップで詳しく見る</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>出典・クレジット <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>3D人体を準備中</strong><span>{progress}% · {atlas?.parts.length.toLocaleString()??'2,234'}個のパーツを読み込み中</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>再読み込み</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'人体'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?localizeAnatomyName(chosen.name):''}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">この器官が属する系統の説明です。</span>}<div className="structure-meta"><span>選択中の3Dパーツ<strong>{state.selected.length.toLocaleString()}個</strong></span></div></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'周囲の人体に戻す':'この構造だけを表示'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>選択を解除</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">出典と収録範囲</div><SheetTitle className="structure-title">人体をひらく。</SheetTitle><SheetDescription>BodyParts3Dの成人男性モデルを、3Dで観察できます。</SheetDescription><div className="about-copy"><p><strong>成人男性 · BodyParts3D</strong><br/>2,234個の選択できる3Dメッシュと、3,432個の構造名を収録しています。</p><p>このモデルはすべての人の体や個人差を表すものではありません。1つの構造名が複数の3Dパーツをまとめている場合があります。</p><p>色と系統分けは観察しやすくするためのものです。Webで動かすために形状は簡略化されており、説明は学習用の一般的な情報です。診断や手術のための資料ではありません。</p><h3>出典</h3><p>BodyParts3D（ライフサイエンス統合データベースセンター）を、CC Attribution 4.0 Internationalの条件で使用しています。</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">データセットのライセンス <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">元の形状とメタデータ <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">元の研究論文 <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
