import type {Atlas} from './anatomy';
import type {LessonId} from './learning';
export type SchoolLevel='middle'|'basic'|'biology';
export const SCHOOL_LEVELS=[{id:'middle',name:'中学校理科',unit:'第2分野（3）生物の体のつくりと働き／動物の体のつくりと働き',source:'https://www.mext.go.jp/a_menu/shotou/new-cs/1387016.htm'},{id:'basic',name:'高校 生物基礎',unit:'（2）ヒトの体の調節',source:'https://www.mext.go.jp/a_menu/shotou/new-cs/1407074.htm'},{id:'biology',name:'高校 生物',unit:'（4）生物の環境応答／生物基礎との関連',source:'https://www.mext.go.jp/a_menu/shotou/new-cs/1407074.htm'}] as const;
export interface Observation {title:string;names:string[];hint:string}
export interface SchoolTopic {levels:SchoolLevel[];unit:string;goal:string;essential:string[];observations:Observation[];question:string;answer:string;advanced?:string;biology?:string[];basic?:string[]}
export const SCHOOL_TOPICS:Record<LessonId,SchoolTopic>={
 heart:{levels:['middle','basic'],unit:'生命を維持する働き／体内環境',goal:'血液の通り道を、心臓・肺・全身のつながりで説明する。',essential:['心房','心室','弁','動脈','静脈','肺循環','体循環'],observations:[{title:'心臓と肺',names:['heart','left lung','right lung'],hint:'心臓と肺の位置を比べ、肺へ向かう流れと全身へ向かう流れを分けよう。'}],question:'肺動脈を流れる血液は、酸素が多い？ 少ない？ 理由も説明しよう。',answer:'酸素が少ない血液です。右心室から、肺で酸素を受け取る前の血液が送られるからです。動脈は心臓から出る血管を指します。'},
 blood:{levels:['middle','basic'],unit:'生命を維持する働き／免疫',goal:'血液の成分と「運ぶ・守る・止血する」を結びつける。',essential:['赤血球','白血球','血小板','血しょう'],observations:[{title:'血液を運ぶ心臓',names:['heart'],hint:'血球はこの人体の3Dパーツには含まれません。成分の大きさや働きは学習図で確認しよう。'}],question:'赤血球と血しょうは、それぞれ何を運ぶ？',answer:'赤血球は主に酸素を運びます。血しょうは養分、二酸化炭素、不要な物質などを運びます。'},
 respiratory:{levels:['middle','basic'],unit:'生命を維持する働き／体内環境',goal:'空気の通り道と、肺胞での酸素・二酸化炭素の交換を説明する。',essential:['気管','気管支','肺胞','横隔膜','毛細血管'],observations:[{title:'気管から左右の肺へ',names:['trachea','left lung','right lung'],hint:'左右の肺につながる気管を見つけよう。肺胞の微細な構造は学習図で確認します。'},{title:'肺と横隔膜',names:['left lung','right lung','diaphragm'],hint:'肺の下にある横隔膜を確認し、胸の容積の変化を考えよう。'}],question:'肺胞が多数あることは、ガス交換にどんな利点がある？',answer:'血液と空気が接する面積が大きくなり、酸素と二酸化炭素を交換しやすくなります。'},
 urinary:{levels:['middle','basic','biology'],unit:'生命を維持する働き／体内環境',goal:'血液から尿がつくられ、体外へ出る経路をたどる。',essential:['腎臓','尿管','ぼうこう','尿道','尿素'],observations:[{title:'尿の通り道を立体で',names:['left kidney','right kidney','ureter','urinary bladder','urethra'],hint:'背中側にある腎臓から、尿管・ぼうこう・尿道の位置をたどろう。'}],question:'尿素をつくる器官と、尿として体外へ出す働きをする器官は同じ？',answer:'異なります。尿素は主に肝臓でつくられ、血液で腎臓に運ばれ、尿として排出されます。',basic:['腎臓は不要物の排出だけでなく、水分や無機塩類の量を調節し、体内環境の維持を助けます。','発展：腎単位（ネフロン）では、ろ過と再吸収が行われます。必要な物質のすべてを尿に捨てるわけではありません。'],biology:['生物基礎の復習：水分・無機塩類の調節を、体内環境の維持と関連づけます。'],advanced:'ネフロンの細かな形は収録3Dにありません。ろ過・再吸収は発展の模式説明です。'},
 liver:{levels:['middle','basic','biology'],unit:'生命を維持する働き／神経系と内分泌系による調節',goal:'肝臓の位置と、養分・血液・胆汁の通り道を区別する。',essential:['肝臓','胆汁','胆のう','門脈'],observations:[{title:'肝臓・胆のう・すい臓',names:['liver','gallbladder','pancreas'],hint:'肝臓は腹部の右上。胆のうは胆汁を蓄えます。すい臓は別の器官です。'},{title:'肝臓と出入りする血管',names:['liver','hepatic portal vein','hepatic artery','hepatic vein'],hint:'門脈と肝動脈は血液を肝臓へ運び、肝静脈は血液を肝臓から運び出します。'},{title:'胆汁の通り道',names:['gallbladder','common hepatic duct','bile duct','duodenum'],hint:'胆汁は肝臓でつくられ、胆管を通って十二指腸へ届きます。血液の通り道と区別しよう。'}],question:'肝臓へ入る血液と、肝臓でつくられる胆汁は同じ管を流れる？',answer:'別の管です。血液は門脈・肝動脈・肝静脈などの血管を流れ、胆汁は胆管を通って十二指腸へ流れます。',basic:['肝臓はグルコースをグリコーゲンとして蓄えたり、グリコーゲンを分解してグルコースを血液に供給したりします。','すい臓のホルモンなどと肝臓の働きが連携し、血糖濃度の調節に関わります。','アミノ酸の分解などで生じる有害なアンモニアは、主に肝臓で尿素へ変えられ、腎臓から排出されます。'],biology:['生物基礎との関連：肝臓を、代謝と血糖濃度の調節を担う器官として捉えます。','発展観察：肝小葉では血液と胆汁の流れる方向が異なります。下の拡大模式図で比べます。'],advanced:'肝小葉は理解を助ける発展内容です。細かな組織構造の暗記を、指導要領上の一律の必須事項とはしていません。'},
 eye:{levels:['middle','biology'],unit:'刺激と反応／動物の反応と行動',goal:'光を受け取る構造と、脳へ情報を伝える経路を説明する。',essential:['角膜','虹彩','瞳孔','水晶体','網膜','視神経'],observations:[{title:'眼球と視神経',names:['right eye','right optic nerve'],hint:'目の後ろから脳へ向かう視神経を確認しよう。眼球内は専用3D模型で分解できます。'}],question:'水晶体と網膜は、それぞれどんな働きをする？',answer:'水晶体は光を屈折させて網膜に像を結ぶ働きをし、網膜は光を受け取って神経の信号に変える働きをします。',biology:['受容器が刺激を受け取り、神経の情報が中枢へ伝わる仕組みを、視覚を例に考えます。','桿体細胞は暗い所での見え方、錐体細胞は色や細かな形の見分けに関わります。','ピントの調節と、瞳孔による光量の調節は別の働きです。']},
 ear:{levels:['middle','biology'],unit:'刺激と反応／動物の反応と行動',goal:'音の振動が神経の情報に変わり、脳へ伝わる経路をたどる。',essential:['外耳道','鼓膜','耳小骨','うずまき管','聴神経'],observations:[{title:'耳と脳の位置',names:['external ear','brain'],hint:'耳の位置と脳との関係を確認。鼓膜・耳小骨・うずまき管は収録3Dにないため、下の断面模式図で観察します。'}],question:'音の振動は、耳小骨から直接脳へ届く？',answer:'いいえ。耳小骨の振動はうずまき管へ伝わり、そこで神経の情報に変わって聴神経を通り脳へ伝わります。',biology:['うずまき管（蝸牛）の有毛細胞が振動を受け取り、神経の情報へ変える仕組みにつなげます。','三半規管と前庭は、体の動きや傾きなどを感じる平衡感覚に関わります。聴覚の経路と区別しましょう。'],advanced:'耳小骨の個別名（つち骨・きぬた骨・あぶみ骨）や有毛細胞の細部は発展内容です。'},
 nervous:{levels:['middle','basic','biology'],unit:'刺激と反応／神経系と内分泌系による調節／動物の反応',goal:'感覚神経・中枢神経・運動神経を結び、反射と意識的な反応を比べる。',essential:['脳','せきずい','感覚神経','運動神経','反射'],observations:[{title:'脳とせきずい',names:['brain','spinal cord'],hint:'中枢神経が体のどこにあるかを、前と後ろから確認しよう。'}],question:'反射では脳に情報がまったく伝わらない？',answer:'脳にも情報は伝わります。手を引く反射の命令は、脳で意識的に判断する前に、せきずいを介した経路で筋肉へ伝わります。',basic:['自律神経系とホルモンによる調節を、体内環境の維持と結びつけます。','神経は情報を伝え、内分泌腺が出すホルモンは血液で運ばれます。'],biology:['ニューロンが情報を伝える仕組みと、シナプスを介した伝達につなげます。','受容器から中枢、効果器へ至る経路を、反射と意識的な反応で比較します。']},
 digestive:{levels:['middle'],unit:'生命を維持する働き',goal:'消化管をたどり、消化と吸収の違いを説明する。',essential:['食道','胃','小腸','大腸','消化酵素','柔毛'],observations:[{title:'消化管をたどる',names:['esophagus','stomach','small intestine','large intestine'],hint:'食物の通り道を順に確認。肝臓やすい臓の中を食物が通るわけではありません。'},{title:'消化を助ける器官',names:['liver','gallbladder','pancreas','duodenum'],hint:'消化液をつくる器官と、食物の通り道とのつながりを考えよう。'}],question:'消化と吸収は、何が違う？',answer:'消化は食物を吸収できる小さな物質へ分解すること、吸収はその物質を小腸の壁などから体内に取り込むことです。'},
 movement:{levels:['middle','biology'],unit:'刺激と反応／動物の反応と行動',goal:'骨・関節・筋肉の位置と、筋肉の収縮による動きを結びつける。',essential:['骨','関節','筋肉','けん'],observations:[{title:'右腕の骨と筋肉',names:['right humerus','right radius','right ulna','short head of right biceps brachii','long head of right biceps brachii','long head of right triceps brachii','lateral head of right triceps brachii','medial head of right triceps brachii'],hint:'筋肉は骨に付着し、縮んで骨を引きます。3Dは静止形状なので、曲げ伸ばしは学習図で比べます。'}],question:'肘を伸ばすとき、筋肉は骨を押している？',answer:'筋肉は骨を押すのではなく、収縮して引きます。曲げる筋肉と伸ばす筋肉が協調して働きます。',biology:['効果器としての骨格筋を、運動神経からの情報と関連づけます。','発展：筋収縮ではアクチンとミオシンの相互作用によって力が生じます。']},
 homeostasis:{levels:['basic','biology'],unit:'神経系と内分泌系による調節（生物基礎）',goal:'すい臓のホルモンと肝臓の働きから、血糖濃度を保つ仕組みを説明する。',essential:['恒常性','ホルモン','インスリン','グルカゴン','グリコーゲン'],observations:[{title:'肝臓とすい臓の位置',names:['liver','pancreas'],hint:'離れた器官同士が、血液で運ばれるホルモンを通して連携します。'}],question:'食後と空腹時で、肝臓のグリコーゲンの扱いはどう変わる？',answer:'食後はインスリンの働きなどによりグリコーゲン合成が促進されます。空腹時はグルカゴンの働きなどによりグリコーゲン分解とグルコースの供給が促進されます。',basic:['血糖濃度の変化に応じてホルモン分泌が変わり、元の範囲へ戻す方向に働きます。これを負のフィードバックと関連づけます。','肝臓・すい臓だけでなく、筋肉や脂肪組織、自律神経なども血糖濃度の調節に関わります。','糖尿病では、インスリンの分泌や働きが十分でないために血糖濃度が高くなります。体の調節と身近な疾患を関連づけます。'],biology:['生物基礎の復習：代謝や細胞の働きと、個体の恒常性を関連づけます。']},
 immune:{levels:['basic'],unit:'免疫',goal:'自然免疫と獲得免疫を、体を守る仕組みとして区別する。',essential:['自然免疫','獲得免疫','抗原','抗体','免疫記憶'],observations:[{title:'脾臓（ひ臓）の位置',names:['spleen'],hint:'血液や免疫に関わる器官の一つです。免疫細胞は人体の3Dパーツに含まれません。'}],question:'同じ病原体に再び出会ったとき、獲得免疫が速く働くのはなぜ？',answer:'初回の反応で生じた記憶細胞などが残り、同じ抗原に対してすばやく強く反応できるためです。',basic:['自然免疫は食作用などで異物に対応します。獲得免疫は抗原に応じた反応と免疫記憶を特徴とします。','抗体を使う体液性免疫と、感染した細胞などに作用する細胞性免疫を区別します。','予防接種は免疫記憶を利用する例です。花粉症などのアレルギーは、免疫反応が生活に影響する例です。']}
};

export function observationIds(atlas:Atlas,names:string[]):string[]{
 const wanted=new Set(names.map(n=>n.toLowerCase())),known=new Set(atlas.parts.map(p=>p.id));
 return [...new Set(atlas.concepts.filter(c=>wanted.has(c.name.toLowerCase())).flatMap(c=>c.elements).filter(id=>known.has(id)))];
}
export function curriculumRelation(id:LessonId,level:SchoolLevel){
 if(level==='basic'&&['heart','blood','respiratory','urinary'].includes(id))return '中学校の復習・体内環境との関連';
 if(level==='biology'&&['urinary','liver','homeostasis'].includes(id))return '生物基礎の復習・発展観察';
 if(level==='biology'&&id==='ear')return '刺激の受容と反応の関連例';
 return 'この科目の学習につながる観察';
}
